apiVersion: v1
kind: Secret
metadata:
  name: diffusion-secrets
  namespace: diffusion
type: Opaque
data:
  POSTGRES_PASSWORD: RGlmZlVzMTBuX1MzY3VyM18yMDI2IQ==
  REDIS_PASSWORD: UjNkMXNfRDFmZnVzMTBuXzIwMjYh
  N8N_ENCRYPTION_KEY: NGE3ZjJlOWIxYzhkM2Y2YTVlMmI5YzRkN2YxYThlM2I2YzlkMmY1YThiMWU0YzdkMGYzYTZiOWMyZTVmOGEx
  PGADMIN_EMAIL: cm1pbGl5YWh5YTJAZ21haWwuY29t
  PGADMIN_PASSWORD: YWRtaW4xMjM=
  VAULT_TOKEN: VjR1bHRfUjAwdF9UMGszbl8yMDI2IQ==
  KONG_JWT_SECRET: Q2wzX1MzY3IzdDNfQjFpbmQzZV8yMDI2X1NVUEVSX1NFQ1JFVF9LRVkh
