apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-grafana
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GF_ADMIN_PASSWORD
      remoteRef:
        key: diffusion/REPLACE_ENV/grafana
        property: GF_ADMIN_PASSWORD
