apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: observability
spec:
  type: ExternalName
  externalName: postgres.data.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: observability
spec:
  type: ExternalName
  externalName: redis.data.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-main
  namespace: observability
spec:
  type: ExternalName
  externalName: n8n-main.app.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: observability
spec:
  type: ExternalName
  externalName: queue-service.app.svc.cluster.local
