apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - monitoring.yaml
  - prometheus-cm.yaml
  - external-services.yaml
commonLabels:
  layer: observability
  app.kubernetes.io/part-of: diffusion-platform
