apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - pvcs.yaml
  - monitoring.yaml
  - configmap-prometheus.yaml
  - configmap-prometheus-rules.yaml
  - configmap-grafana-datasources.yaml
  - configmap-grafana-dashboards.yaml
  - external-services.yaml
  - external-secret-grafana.yaml
commonLabels:
  layer: observability
  app.kubernetes.io/part-of: diffusion-platform
