apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc
  namespace: diffusion
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
