apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diffusion

resources:
  - ../../base

patches:
  - path: patches/ingress-host-prod.yaml
    target:
      kind: Ingress
      name: diffusion-ingress
  - path: patches/increase-replicas.yaml
  - path: patches/storage-class-gp3.yaml
  - path: patches/hpa-prod.yaml

commonLabels:
  environment: prod

images:
  - name: diffusion-queue-service
    newTag: v1.0.0
