apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: vault-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: diffusion/REPLACE_ENV/vault
        property: VAULT_TOKEN
