apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - namespace.yaml
  - external-secret-vault.yaml
  - vault.yaml
commonLabels:
  layer: security
  app.kubernetes.io/part-of: diffusion-platform
