# Supprime tous les ExternalSecret et ClusterSecretStore en dev
# (pas d'AWS Secrets Manager sur Docker Desktop / Minikube)
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-data
  namespace: data
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-pgadmin
  namespace: data
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-app
  namespace: app
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-gateway
  namespace: gateway
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-grafana
  namespace: observability
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault
  namespace: security
---
$patch: delete
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
---
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
