apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  namespace: diffusion
spec:
  replicas: 1
---
$patch: delete
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: n8n-worker-hpa
  namespace: diffusion
