apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              memory: "512Mi" # Reduced by 50%
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            limits:
              memory: "256Mi" # Reduced by 50%
            requests:
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  
spec:
  template:
    spec:
      containers:
        - name: n8n-main
          resources:
            limits:
              memory: "512Mi" # Reduced by 50%
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  
spec:
  template:
    spec:
      containers:
        - name: n8n-worker
          resources:
            limits:
              memory: "512Mi" # Reduced by 50%
