apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base
  - patches/nodeports.yaml
  - local-secrets.yaml

patches:
  - path: patches/queue-service-image-local.yaml
    target:
      kind: Deployment
      name: queue-service
  - path: patches/prometheus-config-dev.yaml
    target:
      version: v1
      kind: ConfigMap
      name: prometheus-config
  - path: patches/ingress-host-localhost.yaml
    target:
      kind: Ingress
      name: diffusion-ingress
  - path: patches/reduce-replicas.yaml
  - path: patches/reduce-resources.yaml
  - path: patches/disable-external-secrets.yaml
  - path: patches/postgres-dev.yaml
    target:
      kind: StatefulSet
      name: postgres
  - path: patches/redis-dev.yaml
    target:
      kind: StatefulSet
      name: redis
  - path: patches/flyway-wait-postgres.yaml
    target:
      kind: Job
      name: flyway-migration
  - path: patches/kong-dev.yaml
    target:
      kind: Deployment
      name: kong
  - target:
      kind: Deployment
      name: vault
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe
        value:
          tcpSocket:
            port: 8200
          failureThreshold: 30
          periodSeconds: 5
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          tcpSocket:
            port: 8200
          periodSeconds: 30
          failureThreshold: 3
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          tcpSocket:
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
  - target:
      namespace: data
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-data
  - target:
      namespace: app
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-app
  - target:
      namespace: gateway
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-gateway
  - target:
      namespace: observability
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-observability
  - target:
      namespace: security
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-security
  - target:
      namespace: external-secrets
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-external-secrets
  - target:
      kind: Namespace
      name: data
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-data
  - target:
      kind: Namespace
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-app
  - target:
      kind: Namespace
      name: gateway
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-gateway
  - target:
      kind: Namespace
      name: observability
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-observability
  - target:
      kind: Namespace
      name: security
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-security
  - target:
      kind: Namespace
      name: external-secrets
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-external-secrets
  - target:
      kind: Service
      name: postgres
      namespace: app
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-postgres.dev-data.svc.cluster.local
  - target:
      kind: Service
      name: redis
      namespace: app
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-redis.dev-data.svc.cluster.local
  - target:
      kind: Service
      name: n8n-main
      namespace: gateway
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-n8n-main.dev-app.svc.cluster.local
  - target:
      kind: Service
      name: postgres-exporter
      namespace: observability
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-postgres.dev-data.svc.cluster.local
  - target:
      kind: Service
      name: redis-exporter
      namespace: observability
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-redis.dev-data.svc.cluster.local
  - target:
      kind: Service
      name: n8n-main
      namespace: observability
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-n8n-main.dev-app.svc.cluster.local
  - target:
      kind: Service
      name: queue-service
      namespace: observability
    patch: |-
      - op: replace
        path: /spec/externalName
        value: dev-queue-service.dev-app.svc.cluster.local


configMapGenerator:
  - name: n8n-config
    behavior: merge
    namespace: app
    literals:
      - LOG_LEVEL=debug
      - N8N_LOG_LEVEL=debug
      - EXECUTIONS_DATA_MAX_AGE=24
      - N8N_CONCURRENCY_PRODUCTION_LIMIT=5
      - DB_POSTGRESDB_HOST=dev-postgres
      - QUEUE_BULL_REDIS_HOST=dev-redis
  - name: queue-service-config
    behavior: merge
    namespace: app
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=development
      - REDIS_HOST=dev-redis
      - N8N_WEBHOOK_BASE_URL=http://dev-n8n-main:5678

generatorOptions:
  disableNameSuffixHash: true

labels:
  - includeSelectors: true
    pairs:
      environment: dev

images:
  - name: n8nio/n8n
    newTag: "2.18.7"
  - name: postgres
    newTag: "16.6-alpine"
  - name: redis
    newTag: "7.4.1-alpine"
  - name: ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/diffusion-queue-service
    newName: diffusion-queue-service
    newTag: "dev"
  - name: kong
    newTag: "3.6.1"
  - name: hashicorp/vault
    newTag: "1.15.6"
  - name: prom/prometheus
    newTag: "v2.51.0"
  - name: grafana/grafana
    newTag: "10.4.18"
