apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app
spec:
  type: ExternalName
  externalName: postgres.data.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app
spec:
  type: ExternalName
  externalName: redis.data.svc.cluster.local
