apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - n8n-main.yaml
  - n8n-worker.yaml
  - queue-service.yaml
  - external-services.yaml
  - external-secret-app.yaml
  - configmap-n8n.yaml
  - configmap-queue-service.yaml
commonLabels:
  layer: app
  app.kubernetes.io/part-of: diffusion-platform
