apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    # Cette annotation sera SURCHARGÉE par chaque overlay
    # avec l'ARN du rôle IAM correspondant à l'environnement
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/REPLACE_ME
